image:
  - Visual Studio 2019

version: 5.0.0.{build}

configuration: Release

before_build:
- nuget restore

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
- provider: NuGet
  server: https://www.myget.org/F/autofac/api/v2/package
  api_key:
    secure: rCUEY75fXN0wxtMy6QL4jCrLdaYbxIBzIXWeN+wEu/XDpyqimzreOc5AH5jMd5ah
  skip_symbols: true
  symbol_server: https://www.myget.org/F/autofac/symbols/api/v2/package
